# Remap prefix to Ctrl+a (like screen)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Set mouse on
set -g mouse on

# List of Pluggins
#set -g @plugin 'catppuccin/tmux#latest'
#set -g @plugin 'tmux-plugins/tpm'
#set -g @catppuccin_flavor 'mocha'

# Split panes using | and -
bind | split-window -h
bind - split-window -v
# Reload tmux config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
# Other screen-like keybindings
bind c new-window
bind n next-window
bind p previous-window
bind k kill-window

# don't rename windows automatically
set-option -g allow-rename off
set-option -g automatic-rename off
# Initialize TMUX pluggin manager
#run '~/.tmux/plugins/tpm/tpm'
setw -g mode-keys vi

# copy in tmux
# press ctrl+a [ to enter copy mode
# press space to enter the selection mode
# press enter to copy
# presss ctrl+a ] to paste 

bind -n C-x setw synchronize-panes on
bind -n M-x setw synchronize-panes off

# control-x to turn it on
# alt-x to turn it off

# Copy to clipboard
#bind-key -T copy-mode Enter send -X copy-pipe-and-cancel "wl-copy"

set-option -g set-clipboard on
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe "wl-copy"
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode MouseDragEnd1Pane send -X copy-pipe "wl-copy"

# Plugin list (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

# Catppuccin flavor and layout
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_pane_status_enabled "yes"
set -g @catppuccin_pane_border_status "yes"

# Catppuccin status modules
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_modules_right "user shell cpu ram network uptime battery date time"

# Optional: Extend space for long status lines
set -g status-left-length 100
set -g status-right-length 150

# Load TPM
run '~/.tmux/plugins/tpm/tpm'

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
